version: '3'

services:
  db:
    image: postgres

  web:
    image: cjkorver/backend
    build: .
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      -db

  wait:
    image: waisbrot/wait
    environment:
      - TARGETS=db:5432
