# Generated by Django 2.0.2 on 2018-03-03 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_User_Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Auth_User_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT', max_length=50)),
                ('description', models.CharField(default='DEFAULT', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Case_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Case_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT', max_length=50)),
                ('description', models.CharField(default='DEFAULT', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='DEFAULT', max_length=50)),
                ('last_name', models.CharField(default='DEFAULT', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('street_address', models.CharField(default='DEFAULT', max_length=50)),
                ('city', models.CharField(default='DEFAULT', max_length=50)),
                ('state', models.CharField(default='WA', max_length=2)),
                ('zipcode', models.CharField(default='DEFAULT', max_length=10)),
                ('country', models.CharField(default='DEFAULT', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT', max_length=50)),
                ('description', models.CharField(default='DEFAULT', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT', max_length=50)),
                ('description', models.CharField(default='DEFAULT', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT', max_length=50)),
                ('description', models.CharField(default='DEFAULT', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.Status'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.Event_Type'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.Client_Type'),
        ),
        migrations.AddField(
            model_name='case_event',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.Event'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.Case_Type'),
        ),
        migrations.AddField(
            model_name='case',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.Client'),
        ),
        migrations.AddField(
            model_name='auth_user_case',
            name='case_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.Case'),
        ),
        migrations.AddField(
            model_name='auth_user_case',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
