# Generated by Django 2.0.2 on 2018-02-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
