# Generated by Django 2.0.2 on 2018-03-06 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth_user_case',
            old_name='case_id',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='auth_user_case',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='case_type_id',
            new_name='case_type',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='case_event',
            old_name='case_id',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='case_event',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_type_id',
            new_name='client_type',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_status_id',
            new_name='event_status',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_type_id',
            new_name='event_type',
        ),
    ]
