# Generated by Django 2.0.2 on 2018-04-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20180306_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_type_name',
            field=models.CharField(default='DEFAULT', max_length=50),
        ),
    ]
