# Generated by Django 2.0.2 on 2018-04-10 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_remove_case_case_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT', max_length=50)),
                ('description', models.CharField(default='DEFAULT', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT', max_length=50)),
                ('description', models.CharField(default='DEFAULT', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_type',
        ),
        migrations.AddField(
            model_name='case',
            name='case_number',
            field=models.CharField(default='0000000000', max_length=50),
        ),
        migrations.AddField(
            model_name='case_charge',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.Case'),
        ),
        migrations.AddField(
            model_name='case_charge',
            name='charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.Charge'),
        ),
        migrations.AddField(
            model_name='event',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.Court'),
        ),
    ]
