# Generated by Django 2.0.2 on 2018-04-25 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0010_auto_20180424_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
    ]
