# Generated by Django 2.0.2 on 2018-04-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0012_auto_20180428_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='offense',
            name='trigger',
            field=models.CharField(default='00', max_length=10),
        ),
    ]
