# Generated by Django 2.0.2 on 2018-04-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0015_auto_20180428_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='dateOfBirth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='streetAddress',
            new_name='street_address',
        ),
    ]
