# Generated by Django 2.0.2 on 2018-04-29 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0020_auto_20180429_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='caseNumber',
            field=models.CharField(default='0000000000', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sentencecompliance',
            name='violationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Violation'),
        ),
    ]
