# Generated by Django 2.0.2 on 2018-04-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0021_auto_20180429_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='treatmentOrdered',
            field=models.CharField(default='No treatment required', max_length=500),
        ),
    ]
