# Generated by Django 2.0.2 on 2018-04-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0022_case_treatmentordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='payCommunityService',
        ),
        migrations.RemoveField(
            model_name='case',
            name='payWorkCrew',
        ),
        migrations.AddField(
            model_name='fine',
            name='payCommunityService',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fine',
            name='payWorkCrew',
            field=models.BooleanField(default=False),
        ),
    ]
