# Generated by Django 2.0.2 on 2018-05-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0023_auto_20180430_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='caseClosed',
            new_name='isCaseClosed',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='domesticViolence',
            new_name='isDomesticViolence',
        ),
        migrations.RenameField(
            model_name='fine',
            old_name='payCommunityService',
            new_name='isPayCommunityService',
        ),
        migrations.RenameField(
            model_name='fine',
            old_name='payWorkCrew',
            new_name='isPayWorkCrew',
        ),
        migrations.RenameField(
            model_name='sentencecompliance',
            old_name='admit',
            new_name='isAdmit',
        ),
        migrations.RenameField(
            model_name='sentencecompliance',
            old_name='reserve',
            new_name='isReserve',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='motion35',
            new_name='isMotion35',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='motion36',
            new_name='isMotion36',
        ),
    ]
