# Generated by Django 2.0.2 on 2018-05-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0024_auto_20180503_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='punishment',
            name='startDate',
            field=models.DateField(blank=True, default='2000-10-10', null=True),
        ),
    ]
